import gurobipy as gp
import numpy as np
import torch
from gurobipy import GRB

from pygranso.private.osqpTorchAdapter import solve_osqp_torch_qp
from pygranso.private.osqpWorkspace import TorchOSQPWorkspace

QP_REQUESTS = 0
OSQP_TRACE = None


def solveQP(
    H,
    f,
    A,
    b,
    LB,
    UB,
    QPsolver,
    torch_device,
    double_precision,
    osqp_options=None,
):
    """
    solveQP:
        Convenience wrapper for any quadprog interface QP solver.  This
        wrapper function will suppress any warnings from the underlying
        quadprog solver and catch any errors that are thrown and rethrow
        them as specific error types, such that they can be caught and
        dealt with accordingly.

        solveQP also keeps tracks of the number of times:
        - solveQP has called quadprog
        - quadprog has thrown an error or returned an invalid result;
            a result is considered invalid if it is exactly zero, contains
            infs/NaNs, or is empty.

        To access this metadata:
        [requests,errors] = solveQP('counts');

        To reset these counters:
        clear solveQP;

        INPUT:
        same arguments as quadprog plus an additional field to
        quadprog's options struct:

        .suppress_warnings                  [logical | {true}]
            suppress all warnings and error messages generated by
            quadprog (except for license issues)

        OUTPUT:
        X and LAMBDA output arguments from full call to quadprog:
        [X,FVAL,EXITFLAG,OUTPUT,LAMBDA] = quadprog(...)

        If you publish work that uses or refers to PyGRANSO, please cite both
        PyGRANSO and GRANSO paper:

        [1] Buyun Liang, Tim Mitchell, and Ju Sun,
            NCVX: A User-Friendly and Scalable Package for Nonconvex
            Optimization in Machine Learning, arXiv preprint arXiv:2111.13984 (2021).
            Available at https://arxiv.org/abs/2111.13984

        [2] Frank E. Curtis, Tim Mitchell, and Michael L. Overton,
            A BFGS-SQP method for nonsmooth, nonconvex, constrained
            optimization and its evaluation using relative minimization
            profiles, Optimization Methods and Software, 32(1):148-181, 2017.
            Available at https://dx.doi.org/10.1080/10556788.2016.1208749

        solveQP.py (introduced in PyGRANSO v1.0.0)
        Copyright (C) 2016-2021 Tim Mitchell and Buyun Liang

        This file is a MATLAB-to-Python port of solveQP.m from
        GRANSO v1.6.4 with the following new functionality and/or changes:
            1. Replace MATLAB quadprog solver with OSQP https://osqp.org/
        Ported from MATLAB to Python and modified by Buyun Liang, 2021

        For comments/bug reports, please visit the PyGRANSO webpage:
        https://github.com/sun-umn/PyGRANSO

        =========================================================================
        |  PyGRANSO: A PyTorch-enabled port of GRANSO with auto-differentiation |
        |  Copyright (C) 2021 Tim Mitchell and Buyun Liang; 2026 Ryan Devera     |
        |                                                                       |
        |  This file is part of PyGRANSO.                                       |
        |                                                                       |
        |  PyGRANSO is free software: you can redistribute it and/or modify     |
        |  it under the terms of the GNU Affero General Public License as       |
        |  published by the Free Software Foundation, either version 3 of       |
        |  the License, or (at your option) any later version.                  |
        |                                                                       |
        |  PyGRANSO is distributed in the hope that it will be useful,          |
        |  but WITHOUT ANY WARRANTY; without even the implied warranty of       |
        |  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the        |
        |  GNU Affero General Public License for more details.                  |
        |                                                                       |
        |  You should have received a copy of the GNU Affero General Public     |
        |  License along with this program.  If not, see                        |
        |  <http://www.gnu.org/licenses/agpl.html>.                             |
        =========================================================================
    """
    global QP_REQUESTS
    QP_REQUESTS += 1

    if QPsolver == "osqp":
        _record_osqp_qp(H, f, A, b, LB, UB)
        return _solve_osqp_with_warm_state(
            H, f, A, b, LB, UB, torch_device, double_precision, osqp_options
        )

    if QPsolver == "gurobi":
        H = H.cpu().numpy()
        f = f.cpu().numpy()
        if A is not None:
            A = A.cpu().numpy()
        # H,f always exist
        # LB and UB always exist
        #  formulation of QP has no 1/2
        H = H / 2

        nvar = len(f)
        # Create a new model
        m = gp.Model()
        vtype = [GRB.CONTINUOUS] * nvar

        # Add variables to model
        vars = []
        for j in range(nvar):
            vars.append(m.addVar(lb=LB[j], ub=UB[j], vtype=vtype[j]))
        x_vec = np.array(vars).reshape(nvar, 1)

        if np.any(A is not None) and np.any(b is not None):
            Aeq = A
            beq = b
            # Populate A matrix
            expr = gp.LinExpr()
            Ax = Aeq @ x_vec
            expr += Ax[0, 0]
            m.addLConstr(expr, GRB.GREATER_EQUAL, beq)
        else:
            #  no constraint A*x < b
            pass

        solution = np.zeros((nvar, 1))

        # Populate objective: x.THx + f.T x
        obj = gp.QuadExpr()
        xTHx = x_vec.T @ H @ x_vec + f.T @ x_vec
        obj += xTHx[0, 0]
        m.setObjective(obj)

        #  suppress output
        # m.Params.LogToConsole = 0
        m.Params.outputflag = 0
        # m.params.NonConvex = 2

        m.optimize()
        x = m.getAttr("x", vars)
        for i in range(nvar):
            solution[i] = x[i]

        if double_precision:
            torch_dtype = torch.double
        else:
            torch_dtype = torch.float
        solution = torch.from_numpy(solution).to(device=torch_device, dtype=torch_dtype)
        return solution


def getErr():
    # getErr NOT used
    global QP_REQUESTS
    errors = 0
    return [QP_REQUESTS, errors]


def getLastOSQPInfo(workspace=None):
    return None if workspace is None else workspace.last_info


def beginOSQPTrace(capture_data=True):
    global OSQP_TRACE
    OSQP_TRACE = {"capture_data": bool(capture_data), "records": []}


def endOSQPTrace():
    global OSQP_TRACE
    trace = [] if OSQP_TRACE is None else OSQP_TRACE["records"]
    OSQP_TRACE = None
    return trace


def _record_osqp_qp(H, f, A, b, LB, UB):
    if OSQP_TRACE is None:
        return
    tensors = {"H": H, "f": f, "A": A, "b": b, "LB": LB, "UB": UB}
    previous = OSQP_TRACE["records"][-1] if OSQP_TRACE["records"] else None
    record = {
        "index": len(OSQP_TRACE["records"]),
        "n": int(f.numel()),
        "H": _trace_tensor_metadata(H),
        "A": _trace_tensor_metadata(A),
    }
    if OSQP_TRACE["capture_data"]:
        record["qp"] = tuple(
            None
            if tensor is None
            else tensor.detach().cpu().clone()
            if torch.is_tensor(tensor)
            else torch.as_tensor(tensor).detach().cpu().clone()
            for tensor in tensors.values()
        )
    if previous is None or "qp" not in previous or "qp" not in record:
        record["structure_changed"] = previous is not None
        record["matrix_values_changed"] = previous is not None
    else:
        previous_H, _previous_f, previous_A, _previous_b, _previous_LB, _previous_UB = (
            previous["qp"]
        )
        current_H, _current_f, current_A, _current_b, _current_LB, _current_UB = record[
            "qp"
        ]
        structure_same = _same_tensor_structure(previous_H, current_H) and (
            (previous_A is None and current_A is None)
            or _same_tensor_structure(previous_A, current_A)
        )
        record["structure_changed"] = not structure_same
        record["matrix_values_changed"] = not (
            _same_tensor_values(previous_H, current_H)
            and (
                (previous_A is None and current_A is None)
                or _same_tensor_values(previous_A, current_A)
            )
        )
    OSQP_TRACE["records"].append(record)


def _trace_tensor_metadata(tensor):
    if tensor is None:
        return None
    nnz = (
        int(torch.count_nonzero(tensor).item())
        if tensor.layout == torch.strided
        else int(tensor._nnz())
    )
    return {
        "shape": tuple(tensor.shape),
        "layout": str(tensor.layout),
        "dtype": str(tensor.dtype),
        "device": str(tensor.device),
        "nnz": nnz,
    }


def _same_tensor_structure(left, right):
    if left is None or right is None:
        return left is right
    if left.shape != right.shape or left.layout != right.layout:
        return False
    if left.layout == torch.strided:
        return True
    left_csr = left if left.layout == torch.sparse_csr else left.to_sparse_csr()
    right_csr = right if right.layout == torch.sparse_csr else right.to_sparse_csr()
    return torch.equal(left_csr.crow_indices(), right_csr.crow_indices()) and torch.equal(
        left_csr.col_indices(), right_csr.col_indices()
    )


def _same_tensor_values(left, right):
    if not _same_tensor_structure(left, right):
        return False
    if left.layout == torch.strided:
        return torch.equal(left, right)
    left_csr = left if left.layout == torch.sparse_csr else left.to_sparse_csr()
    right_csr = right if right.layout == torch.sparse_csr else right.to_sparse_csr()
    return torch.equal(left_csr.values(), right_csr.values())


def resetOSQPWarmState(workspace=None):
    if workspace is not None:
        workspace.reset()


def _solve_osqp_with_warm_state(
    H,
    f,
    A,
    b,
    LB,
    UB,
    torch_device,
    double_precision,
    osqp_options,
):
    options = _copy_osqp_options(osqp_options)
    workspace = options.pop("workspace", None)
    if workspace is None:
        workspace = TorchOSQPWorkspace()
    if not isinstance(workspace, TorchOSQPWorkspace):
        raise TypeError("osqp_options['workspace'] must be a TorchOSQPWorkspace.")
    settings = options.setdefault("settings", {})
    requested_return_info = bool(settings.get("return_info", False))
    settings["return_info"] = True
    result = solve_osqp_torch_qp(
        H,
        f,
        A,
        b,
        LB,
        UB,
        torch_device,
        double_precision,
        options,
        workspace,
    )
    solution, info = result
    workspace.last_info = info
    return (solution, info) if requested_return_info else solution


def _copy_osqp_options(osqp_options):
    if osqp_options is None:
        return {}
    options = dict(osqp_options)
    if isinstance(options.get("settings"), dict):
        options["settings"] = dict(options["settings"])
    return options
